version: "1"
services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.119.0
    container_name: otelcol
    volumes:
      - ./otelcol.yaml:/etc/otelcol/config.yaml:ro
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4318:4318"   # OTLP/HTTP 수신 (기본 포트)
      - "4317:4317"   # OTLP/gRPC 수신 (원하면 사용)
      - "9464:9464"   # Prometheus 수신
    depends_on:
      - jaeger
    networks:
      - otel-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      # - "6831:6831/udp"
      # - "6832:6832/udp"
      # - "4317:4317" # gRPC
      # - "14268:14268"
      - "14250:14250" # gRPC
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus UI
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana UI
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
