version: "1"
services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.119.0
    container_name: otelcol
    volumes:
      - ./otelcol.yaml:/etc/otelcol/config.yaml:ro
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4318:4318"   # OTLP/HTTP 수신 (기본 포트)
      - "4317:4317"   # OTLP/gRPC 수신 (원하면 사용)
      - "9464:9464"   # Prometheus 수신
    depends_on:
      - jaeger
      - tempo
    networks:
      - otel-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      # - "6831:6831/udp"
      # - "6832:6832/udp"
      # - "4317:4317" # gRPC
      # - "14268:14268"
      - "14250:14250" # gRPC
    networks:
      - otel-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    user: "1000:1000"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - /appdata/storage/tempo:/tmp/tempo
    ports:
      - "3200:3200"     # Tempo HTTP
    networks:
      - otel-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus UI
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1000:1000"
    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana
    ports:
      - "3000:3000" # Grafana UI
    networks:
      - otel-network

  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: otelmon-api
    ports:
      - "8090:8090"
    user: "1000:1000"
    volumes:
      - ./api:/app
      - ./api/logs:/app/logs
    restart: unless-stopped
    networks:
      - otel-network
    environment:
      - TZ=Asia/Seoul
      - LOG_DIR=/app/logs

networks:
  otel-network:
    driver: bridge
